### ISSUE TITLE
PIP install?

### ISSUE THREAD

**Issue by ekansa** [swordapp/python-client-sword2#12]
Any plans to make this available via a PIP package install?

**Comment by Hwesta** [comment]
It actually is available on PyPI https://pypi.python.org/pypi/sword2/0.1.15.cc7c6a42843d but the version is quite old (https://bitbucket.org/beno/python-sword2/commits/cc7c6a42843d27ba3c2e65b04a738005a38a9bcd aka 4c9e2fc161ea46085e97928912dcbe5be7c871e0)  In #8  I've requested a new release.

**Comment by Hwesta** [comment]
In case you didn't see the discussion on #8, a new 0.2.0 release is up on PyPI.

**Comment by richard-jones** [comment]
0.2.1 release today: https://pypi.python.org/pypi/sword2/0.2.1
