### ISSUE TITLE
Accept 202 status code response from SWORD server

### ISSUE THREAD

**Issue by liamkirsh** [swordapp/python-client-sword2#14]
If the SWORD server returns a HTTP/1.1 202 Accepted status code in response to a deposit, the Python SWORD2 client incorrectly recognizes it as an error and ignores the deposit receipt.

The [SWORD 2.0 Profile](https://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html) dictates that upon processing a request, the server `SHOULD return a Deposit Receipt as described in Section 10: Deposit Receipt with the HTTP status code 201 (Created).`

CC @kaplun

**Comment by richard-jones** [comment]
202 is not an accepted response code in SWORDv2 - though the wording of the spec is ambiguous.

There is talk of including 202 explicitly in a revision of the spec, should there be enough motivation in the community to do another iteration.
