### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by Hwesta** [swordapp/python-client-sword2#8]
Can you package a new release onto PyPI?  There's over a year between last release and most recent commit, and I'd like to use some of the new features that have been added.

**Comment by Hwesta** [comment]
Happy to see pull requests being merged again! We're using this library, and would appreciate if we could install from a stable pip version, instead of from a commit in git.  Thanks!

**Comment by richard-jones** [comment]
Yes, this is a good idea, and you challenge me to remember how to do a pypi release :)  So, sometime before the new year, promise!

**Comment by richard-jones** [comment]
For my own reference: http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by Hwesta** [comment]
I found https://packaging.python.org/distributing/ to be very useful, and also very thorough.

I also really appreciated it when maintainers correctly tag the python versions it supports (eg ` "Programming Language :: Python :: 2.6",` or  `Programming Language :: Python :: 2 :: Only` or `Programming Language :: Python :: 3`)

Thanks!

**Comment by richard-jones** [comment]
Ok, we have a new release (0.2.0) on pypi.  I've done a quick review of setup.py/cfg, and the README/LICENSE.  I've taken the liberty of straightening out the licenses, and switching to Apache 2.0 which I hope no one minds (it was MIT and/or BSD before, and there's not a lot in it).

I've also started to migrate the wiki from the original bitbucket repo where this library was created, and its a bit of a mess right now, though shouldn't take much effort to reformat.

**Comment by Hwesta** [comment]
Thank you!  I appreciate the release and I'm looking forward to the wiki update.

**Comment by richard-jones** [comment]
Wiki has now also been reformatted, though note that I haven't spent any significant time reviewing the content.  https://github.com/swordapp/python-client-sword2/wiki

Happy to add collaborators to the project to make the maintenance of these things easier.

**Comment by richard-jones** [comment]
FYI, I made a 0.2.1 release today which fixes a couple of bugs
